### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by hozoin** [NUKIB/maldump#7]
**Describe the bug**
In newest version 0.3.0 maldump can not find module maldump.parsers.kaitai. Version 0.2.0 does not have this problem. I have kaitaistruct installed.

**To Reproduce**
1. pip install maldump
2. Run any maldump command
3. Stack Trace
Traceback (most recent call last):
  File "<frozen runpy\>", line 198, in _run_module_as_main
  File "<frozen runpy\>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Scripts\maldump.exe\__main__.py", line 4, in <module\>
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\__main__.py", line 17, in <module\>
    from maldump.av_manager import AVManager
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\av_manager.py", line 5, in <module\>
    from maldump.avs import (avast, avg, avira, eset, forticlient, gdata,
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\avs\avira.py", line 6, in <module\>
    from maldump.parsers.avira_parser import AviraParser
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\parsers\avira_parser.py", line 5, in <module\>
    from maldump.parsers.kaitai.avira_parser import AviraParser as KaitaiParser
ModuleNotFoundError: No module named 'maldump.parsers.kaitai'

**Expected behavior**
No errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by timmriesen** [comment]
I have the same problem on same OS. Would be glad for a fix.

**Comment by Dashdwg201** [comment]
Same issue still occurring.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\__main__.py", line 17, in <module>
    from maldump.av_manager import AVManager
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\av_manager.py", line 5, in <module>
    from maldump.avs import (avast, avg, avira, eset, forticlient, gdata,
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\avs\avira.py", line 6, in <module>
    from maldump.parsers.avira_parser import AviraParser
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\maldump\parsers\avira_parser.py", line 5, in <module>
    from maldump.parsers.kaitai.avira_parser import AviraParser as KaitaiParser
ModuleNotFoundError: No module named 'maldump.parsers.kaitai'
